[package]
name = "berms-studio"
version.workspace = true
edition.workspace = true
publish = false

[[bin]]
name = "berms-studio"
path = "src/main.rs"

[dependencies]
berms-footage.workspace = true
berms-logs.workspace = true
berms-rides.workspace = true
gpui-kit.workspace = true
rfd.workspace = true
time.workspace = true

[dev-dependencies]
serde_json.workspace = true
